### ISSUE TITLE
Log2 undifined type

### ISSUE THREAD

**Issue by thomatoes50** [DeanoC/gfx_image_impl_basic#1]
same as DeanoC/al2o3_vfile#1 

`src/image.cpp:192` need to use `Math_Log2U32`

**Comment by DeanoC** [comment]
Thanks, fixed.
I've started adding GitHub CI so hopefully these kind of things will mostly go away.
Appreciate the bugs. If you notice any others that haven't been court by CI (still a WIP) let me know
